import Link from "next/link";
import { subscribeNewsletter } from "@/app/actions/communications";
import { db } from "@/lib/db";
export const dynamic = "force-dynamic";
export default async function UpdatesPage() {
  const school=await db.school.findUnique({where:{slug:"petra-academy"}});
  const [stories,announcements]=school?await Promise.all([
    db.publication.findMany({where:{schoolId:school.id,status:"PUBLISHED"},include:{campus:true,category:true},orderBy:{publishedAt:"desc"},take:30}),
    db.announcement.findMany({where:{schoolId:school.id,status:"PUBLISHED",parentFacing:true},include:{campus:true,classArm:{include:{classLevel:true}}},orderBy:{publishedAt:"desc"},take:12}),
  ]):[[],[]];
  return <main><section className="bg-[#fff0f1] px-4 py-14"><div className="mx-auto max-w-6xl"><p className="eyebrow">Petra Academy</p><h1 className="page-title max-w-3xl">News, events and achievements from Awka and Nnewi</h1><p className="page-subtitle">Published school updates and parent announcements in one low-data public page.</p></div></section><div className="mx-auto grid max-w-6xl gap-8 px-4 py-10 lg:grid-cols-[1fr_20rem]"><section><h2 className="text-xl font-black">Latest stories</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{stories.map(x=><Link href={`/updates/${x.slug}`} key={x.id} className="card p-5 transition hover:-translate-y-0.5"><div className="flex gap-2"><span className="pill">{x.kind}</span>{x.campus&&<span className="pill">{x.campus.name}</span>}</div><h3 className="mt-3 text-lg font-black">{x.title}</h3><p className="mt-2 text-sm leading-6 text-[#68707d]">{x.excerpt}</p><p className="mt-4 text-sm font-black text-[#b91118]">Read update →</p></Link>)}{!stories.length&&<p className="empty-state card sm:col-span-2">Published stories will appear here.</p>}</div></section><aside><section className="card p-5"><h2 className="font-black">Parent announcements</h2><div className="mt-3 space-y-4">{announcements.map(x=><article key={x.id}><p className="font-black">{x.title}</p><p className="mt-1 text-sm leading-6 text-[#68707d]">{x.body}</p></article>)}{!announcements.length&&<p className="text-sm text-[#68707d]">No current announcements.</p>}</div></section><section className="card mt-4 p-5"><h2 className="font-black">School newsletter</h2><p className="mt-1 text-sm text-[#68707d]">Join the subscriber list for future approved updates.</p><form action={subscribeNewsletter} className="mt-3 grid gap-2"><input name="name" placeholder="Name (optional)"/><input name="email" type="email" placeholder="Email address" required/><button className="button" type="submit">Subscribe</button></form></section></aside></div></main>;
}
